### ISSUE TITLE
We need to provide better references than the pen-test execution standard because it's corporate focus makes its practices somewhat less useful for at-risk communities.

### ISSUE THREAD

**Issue by seamustuohy** [SAFETAG/SAFETAG#116]
The reference to the PenTest standard in the [operational security section](https://github.com/OpenInternet/SAFETAG/blob/aebc10f54fb472fd6888761261a8ece273169f85/content/guides/operational_security/guidelines.md) does not lead anywhere but to the statement that encryption is not optional and the recommendation of telephone – which in many locations where SAFETAG will be used is not an option (or it is nowhere)

**Comment by joncamfield** [comment]
http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-115.pdf (§7.4: Data Handling) provides more substantial text for reference.  I think the best path is to actually provide some specific guidance and resource links

**Comment by joncamfield** [comment]
Additional resources:
https://securityinabox.org/en/guide/secure-file-storage/
https://ssd.eff.org/en/module/how-delete-your-data-securely-linux

Communicating securely:
https://ssd.eff.org/en/index (cross-platform guides for Signal, WhatsApp, OTR, PGP)
https://medium.com/@mshelton/signal-for-beginners-c6b44f76a1f0
https://medium.com/@mshelton/upgrading-whatsapp-security-386c8ce496d3
https://securityinabox.org/en/guide/thunderbird/windows/
