### ISSUE TITLE
Add a post-it activity to the risk modeling handbook section instead of the more complex post mortum

### ISSUE THREAD

**Issue by seamustuohy** [SAFETAG/SAFETAG#125]
For this section it would be great to map a post-it exercise other than pre-mortem, as pre-mortem may only work in some contexts with imaginative and playful hosts

**Comment by elationfoundation** [comment]
Alternative activities will be provided in the 1.0 release.

**Comment by elationfoundation** [comment]
Risk assessment section has been removed.

**Comment by joncamfield** [comment]
Please re-add risk assessment objective
