### ISSUE TITLE
Include activity on how to create memory dumps of infected computers.

### ISSUE THREAD

**Issue by seamustuohy** [SAFETAG/SAFETAG#134]

**Comment by elationfoundation** [comment]
I have concerns about this. There are very few memory forensics experts in our community with extra time. I think this would essentially be collecting extra data about devices that an auditor can't actually act upon.

**Comment by joncamfield** [comment]
In the potential case that an auditor has a very serious concern and can document IOCs on malware, there may be value in this, but it is outside the normal scope of a SAFETAG audit, and the content captured is both highly sensitive and large (hard to transport).

Suggestion: add opsec discussion on this to user device assessment and/or vuln analysis; add these links as further resources: https://www.circl.lu/pub/tr-22/#memory-acquisition https://www.circl.lu/pub/tr-22/#disk-acquisition

**Comment by elationfoundation** [comment]
We should add this as an activity in the future that way auditors with that capacity and use case have some documentation to use.
