### ISSUE TITLE
remove baseline skills from content and place into individual approaches, merge into adids

### ISSUE THREAD

**Issue by seamustuohy** [SAFETAG/SAFETAG#143]
The baseline skills component is aimed at helping an auditor choose what approach to choose and a trainer on what activities to train on. They should not be included in objectives, but in individual approaches and exercises.

**Comment by joncamfield** [comment]
baseline skills are now in methods (which were formally largely objectives), but seem to currently fit well there, as they tend to overlap all of the relevant exercises currently.
