### ISSUE TITLE
Remove context research section

### ISSUE THREAD

**Issue by seamustuohy** [SAFETAG/SAFETAG#148]
Move content from this into two sections.

Research on safely carrying out the audit & Opsec will go into audit preparation as an activity
Research on threats the organization faces will go into threat assessment as an activity

**Comment by joncamfield** [comment]
@seamustuohy I propose to keep this as a standalone section that is heavily cross-referenced with (and sharing activities with) preparation and threat assessment, as well as capacity assessment (adding an activity to identify, for example, internet coverage/reliability available to the org). Thoughts?

**Comment by seamustuohy** [comment]
My only worry would be about causing confusion on the difference between this section and the other sections if they are too heavily interrelated.
