### ISSUE TITLE
Make contents and README the only files in the SAFETAG repository

### ISSUE THREAD

**Issue by seamustuohy** [SAFETAG/SAFETAG#176]
All build, documentation, styling, and non raw content should be moved to a separate repository. The repository should ONLY contain the actual documentation content.

What would remain in the repository would be 
- en/ (as we add languages we can add more folders in the main directory with translated content.)
  - _the contents of the content folder_
- README.md

**Comment by joncamfield** [comment]
Closing - the build work has been moved to its own repository.  Styles remain in for now, but will be deprecated as SAFETAG moves to a web-based format in the future.
