### ISSUE TITLE
python3.4

### ISSUE THREAD

**Issue by kleper** [SAFETAG/SAFETAG#187]
When you try to compile with python3.4 have the following error:

modules / markdown-pp / markdown-pp.py content / index / index.guide.md build / src / guide.md
Traceback (most recent call last):
   "Modules / markdown-pp / markdown-pp.py", line 7 in <module> File
     import MarkdownPP
   File "/home/kleper/Documentos/Proyectos/0-Karisma/SAFETAG/modules/markdown-pp/MarkdownPP/**init**.py", line 4 in <module>
     MarkdownPP import from MarkdownPP
   File "/home/kleper/Documentos/Proyectos/0-Karisma/SAFETAG/modules/markdown-pp/MarkdownPP/MarkdownPP.py", line 4 in <module>
     from import Processor Processor
ImportError: No module named 'Processor'
Makefile: 126: error in the instructions to the goal 'guide'
make: **\* [guide] Error 1

In order to compile the guides me down to version 2.7 of Python, but maybe it's good to check compatibility with newer versions of Python.

**Comment by elationfoundation** [comment]
Thanks Kleper. It looks like the latest version of the markdownPP upstream package has 3.4 support. I will do some testing to make sure that it works and then merge it into the package.

**Comment by joncamfield** [comment]
Closing here, tracking the issue at https://github.com/OpenInternet/Documentation-Builder/issues/9 ; there is a workaround currently and we are looking at detecting the python and markdown-pp version/status and running commands as appropriate.
