### ISSUE TITLE
Add this intro article to password references

### ISSUE THREAD

**Issue by joncamfield** [SAFETAG/SAFETAG#259]
https://web.archive.org/web/20160609142410/https://www.wired.com/2016/06/hacker-lexicon-password-hashing/a

**Comment by elationfoundation** [comment]
Looks good, Archive didn't seem to save it for some reason.  I tried again. https://web.archive.org/web/20160612010630/http://www.wired.com/2009/10/terminal-man-attends-to-some-business/

**Comment by hackatom** [comment]
This should be it? https://www.wired.com/2016/06/hacker-lexicon-password-hashing

**Comment by seamustuohy** [comment]
Yeah, I just looked at our links again and Jon and I somehow broke all
those links. Here are the archive links for those sites.

https://web.archive.org/web/20170611000620/https://www.wired.com/2016/06/hacker-lexicon-password-hashing/

http://web.archive.org/web/20171013115327/https://www.wired.com/2016/05/password-tips-experts

@joncamfield did I ever put the autoarchiving script into SAFETAG so we
didn't need to use archive links? If not, what repo would a script like
that go in?

**Comment by hackatom** [comment]
@seamustuohy, @joncamfield, that goes through all the links within SAFETAG?

**Comment by joncamfield** [comment]
@seamustuohy Let's ping @jmatsushita to see if that's a module/functionality we can add in to metalsmith ?
