### ISSUE TITLE
Add Resource (Threat Hunting)

### ISSUE THREAD

**Issue by seamustuohy** [SAFETAG/SAFETAG#262]
Threat hunting is a popular topic these days, and there are a lot of people who want to get started but don’t know how. What should they hunt for? How should they perform the hunts? What data will they need to collect?

On the other hand, there are a lot of individuals out there who have written blog posts, conference presentations or whatever that detail some of their favorite hunting procedures. The problem is that these procedures are scattered all over the Internet, and are sometimes hard to find.

That’s why the ThreatHunting Project exists. Here you will find links to a number of different published hunting procedures. It my hope that this will give you some concrete starting points, or if you are an experienced hunter, help you find additional techniques to add to your repertoire.

https://github.com/ThreatHuntingProject/ThreatHunting

**Comment by hackatom** [comment]
From reading the contents of the repository, it seems that it's somewhat similar to incident response.

**Comment by seamustuohy** [comment]
Threat hunting is an active investigation to see if a specific type of
threat is in your environment without an incident to tell you it likely is.
So, the technical aspects of the two approaches are similar. But, the
intention and starting place is different. Its hunting for threats when you
don't know if there are threats to be found. If you have reason to believe
there are threats in your environment then its incident response.

**Comment by hackatom** [comment]
Cool! So this is fine staying here in incident_response reference? As I was looking for other useful resource for threat hunting, I came up with ProtectWise's article: 
https://www.protectwise.com/post/analytics-and-forensics-team-up-for-better-threat-hunting/

I've noticed that we don't have yet a forensic audit item in Safetag. What do you think @joncamfield ?

**Comment by joncamfield** [comment]
Pinging @dlshad , perhaps we are looking at a broader method around deeper technical investigation for high-threat orgs with activities around hunting , dealing with finding (incident response) and forensic "first responder" analysis.

**Comment by dlshad** [comment]
Here you go! #323 # this can be a good starting point maybe? I added (Advanced threat) method and exercise
