### ISSUE TITLE
Potential module: VOIP security?

### ISSUE THREAD

**Issue by joncamfield** [SAFETAG/SAFETAG#266]
Many orgs use (intentionally or not) VOIP for their telephony needs.  @seamustuohy found a useful technical auditing tool to help verify vendor claims and organizational assumptions: https://github.com/sanvil/vsaudit

**Comment by hackatom** [comment]
VoIP phones/communication can be [vulnerable](https://securityintelligence.com/news/researchers-find-voip-phones-vulnerable-to-simple-cyberattacks) and [susceptible](https://us.norton.com/voip-security-a-primer/article) to attacks. It would be great to add this as an additional method.

**Comment by joncamfield** [comment]
I would suggest this should be an exercise/activity as opposed to a method (a method which could be considered would be something broader, such as "communications security" or similar, but it would get very entangled with user device and network security, so would need to be carefully scoped).

In both Method and Exercise/Activity creation, for the content to be compatible with the Content-as-Code conversion (and for easy manipulation and inclusion in the current structure) please copy the template folders and files from /en/templates -- each method and activity come with a pre-set selection of files to be filled out which themselves are copied/referred to from across the framework. (https://github.com/SAFETAG/SAFETAG/blob/master/en/document_matter/CONTRIBUTING.md#creating-a-new-safetag-activity should be useful here)

**Comment by dlshad** [comment]
initial references added at /reference/voip_security.md

**Comment by joncamfield** [comment]
Another reference or potential activity: https://github.com/eurialo/vsaudit (h/t @seamustuohy )
