### ISSUE TITLE
add metadata to flag methods and exercises that can be done remotely

### ISSUE THREAD

**Issue by mfc** [SAFETAG/SAFETAG#275]
methods and exercises that can be tagged with "remote" and/or "verified":

* remote = can be done remotely
* **verified** = can be verified remotely

# methods (#remote assumed)

**[vulnerability scanning](https://github.com/OpenInternet/SAFETAG/blob/master/en/methods/vulnerability_scanning/)** (not intranet servers) = #verified

context research
pre-audit questionnaire
reconnaissance
data assessment
threat assessment
risk modeling
capacity assessment (not informal conversations)

# exercises (#remote assumed)

**[cms version](https://github.com/OpenInternet/SAFETAG/tree/master/en/exercises/cms_version)** = #verified
**[check mail server vulns](https://github.com/OpenInternet/SAFETAG/tree/master/en/exercises/check_mail_server_vulns)** = #verified (needs to be changed to remote practice, see #274)
**[dns zone transfer](https://github.com/OpenInternet/SAFETAG/tree/master/en/exercises/dns-zone-transfer)** = #verified (needs privileged access?)
**[insecure website login](https://github.com/OpenInternet/SAFETAG/tree/master/en/exercises/insecure_website_login)** = #verified
**[manual recon](https://github.com/OpenInternet/SAFETAG/tree/master/en/exercises/manual_recon)** = #verified
**[mx record search](https://github.com/OpenInternet/SAFETAG/tree/master/en/exercises/mx-record-search)** = #verified

assessment plan
passive reconnaissance
check config files (not intranet servers, requires privileged remote access)
confidentiality agreement
day in the life
follow up meeting
identify useful resources
incident response
regional context research 
interviews
long term follow up
making introductions
capacity assessment checklist 
staff feedback survey
threat identification
vulnerabiliy research
vulnerability scanning

--------------

this came out of the Feb SAFETAG event :calendar: :factory: :computer: :cloud_with_rain: 

cc: @rolegio

**Comment by joncamfield** [comment]
Closing as this has been implemented!
