### ISSUE TITLE
Create "Generally Accepted Assessor Standards"

### ISSUE THREAD

**Issue by seamustuohy** [SAFETAG/SAFETAG#276]
Came across the "Generally Accepted Auditing Standards" for financial audits today. It's an interesting idea that might be a nice start for talking about what the community sees as basic standards for what is considered an appropriate assessment. 

https://en.wikipedia.org/wiki/Generally_Accepted_Auditing_Standards
https://www.aicpa.org/Research/Standards/AuditAttest/DownloadableDocuments/AU-00150.pdf
http://www.becker.com/sites/default/files/a1_new_topic_pages_67-77.pdf

**Comment by joncamfield** [comment]
I believe the Community Standards and Auditor CoC (https://github.com/SAFETAG/SAFETAG/blob/master/en/document_matter/CODE_OF_CONDUCT.md) address this.
