### ISSUE TITLE
Which Cost-effective vulnerability scanner do I use?

### ISSUE THREAD

**Issue by emmanuelokochu** [SAFETAG/SAFETAG#277]
Hi. I am setting up a team to deliver SAFETAG audits to clients and we are on a tight budget. I see that OPENVAS only runs on linux and I don't want to go that route.

Are there any other FREE scanning tools I can consider? Or any other cheaply available ones.

Thanks

**Comment by rorymbyrne** [comment]
Well you can do quite a lot with the Nessus Home versions. Up to 16 IP addresses and quite a lot of the most useful functionality. 
https://www.tenable.com/products/nessus-home

They also do a pretty good donation for non-profits - you get the professional version for a free for a few years if I recall.
https://support.tenable.com/quoterequestForm_501c3.php

You can also get a Nexpose Community version for one year.
https://www.rapid7.com/info/nexpose-community/

**Comment by joncamfield** [comment]
Thanks Rory for the links! I'd marked this as read and forgot to return to it.

You can also run OpenVAS in a virtual machine, but take care to ensure that the database is stored on an encrypted filesystem and part of your per-audit data management process.

If you're really on a tight budget or timeline, I would consider focusing on higher level tools and organizational process / information mapping work as opposed to a deep-dive into patch level/vuln scanning, as you're almost guaranteed to find vulnerabilities, not unlikely to cause system damage/downtime, and might miss more important or "core" vulnerabilities. Spending money and time to get a comprehensive list of every possible CVE is wasteful when the actual solution is "upgrade to the current wordpress" or "this is a critical system that's no longer updated and has no affordable upgrade path, so we need to airgap it."  

All of this, as always, depends on the capacity and existing security practices of the org as well as what threats they face.

**Comment by emmanuelokochu** [comment]
Thanks guys.

Appreciate this… 

-------
Emmanuel
