### ISSUE TITLE
review language to make more gender neutral

### ISSUE THREAD

**Issue by megdeb** [SAFETAG/SAFETAG#279]
came up as i was reviewing the draft agreement.

**Comment by seamustuohy** [comment]
[Wow, you are right.](https://github.com/SAFETAG/SAFETAG/blob/75b60e7a43ca1353072073becf39ab66b9f92fcc/en/templates/audit/audit/engagement_agreement.md)  Thanks for catching that!

**Comment by joncamfield** [comment]
Also https://github.com/SAFETAG/SAFETAG/search?utf8=%E2%9C%93&q=%22he+%22&type=

**Comment by joncamfield** [comment]
I think I've cleaned it all out (except for some lorem ipsum text that includes "his" :) Closing, please re-open if anyone stumbles across more gendered language in SAFETAG.
