### ISSUE TITLE
Incorporate CUPS password survey into data assessment component

### ISSUE THREAD

**Issue by seamustuohy** [SAFETAG/SAFETAG#28]
We need a way to evaluate password strength. CMU's CUPS program used a password survey that had decent results when compared to their later projects with mechanical turks and does not require getting the full password from the clients (which is needed.)

[Initial survey](https://cups.cs.cmu.edu/soups/2010/proceedings/a2_shay.pdf#page=14)

[Mechanical Turk Questions](http://cups.cs.cmu.edu/soups/2006/proceedings/p67_kuo.pdf#page=10)

**Comment by joncamfield** [comment]
Password Survey at https://github.com/OpenInternet/SAFETAG/blob/master/en/exercises/password_security/password_survey.md is partially modeled off of this; but needs to be added to reference.
