### ISSUE TITLE
Add a table of contents and and index for faster referencing

### ISSUE THREAD

**Issue by rorymbyrne** [SAFETAG/SAFETAG#281]
Love SAFETAG but using it a lot at the moment and finding hard to quickly navigate without having a contents and index.

**Comment by joncamfield** [comment]
Great feedback!  We're actually in the process of working with iilab on a new "interface" for SAFETAG.  You can see a very preliminary  version at https://contentascode.github.io/safetag/@safetag/toolkit/ . We'll be doing outreach for feedback soon, but if you have ideas/feature requests/etc. there's no need to wait.

In the meantime, you might find this handy: https://safetag.org/guide/ -- it's essentially an HTML version of the full PDF guide with a ToC.

**Comment by rorymbyrne** [comment]
Sweet, this is awesome!
