### ISSUE TITLE
Latest "Releases" is 0.4 in 2015

### ISSUE THREAD

**Issue by rorymbyrne** [SAFETAG/SAFETAG#293]
I know there are a lot of moving parts in SAFETAG at the moment but the last complete release on the website/Github is 0.4 in 2015. Might make sense to have full versions available in .pdf so people don't have to go through the installation setup etc.
 
https://github.com/SAFETAG/SAFETAG/releases

**Comment by joncamfield** [comment]
I've pushed an updated version of the full guide PDF in English: https://github.com/SAFETAG/SAFETAG/releases/tag/v0.4.1
