### ISSUE TITLE
Web Application Assessment

### ISSUE THREAD

**Issue by hackatom** [SAFETAG/SAFETAG#309]
Web application assessment is quite a huge task specially if it's going to be done in a wide application. Moving all web-apps-testing-related could be a good way to categorize both exercises and methodologies.

**Comment by joncamfield** [comment]
Some of this exists in the content on vulnerability scanning and the recon work (identifying CMS/host/etc.) , but it is definitely not robust.  I would like to see a lightweight "most common problems" peek at non-standard-CMS-built sites (we have some baseline Drupal/WP/Plone benchmarking), plus a section on applying OWASP ZAP or similar tools would be great (obviously with some caveats) cc'ing in @dlshad , as he's been doing a lot of this work on recent audits.

**Comment by hackatom** [comment]
@joncamfield, Can we rename the /exercises/vulnerability_scanning folder into /exercises/web_vulnerability_scanning?

**Comment by joncamfield** [comment]
Let's actually make a new exercise (or collection of them) for websites - I think there's some good content in the repo to pull together around CMS version testing (and then researching known vulns through CVE searching), and a gap for non-CMS sites (custom built, closed source, etc.) and taking some manual and automatic (but lightweight!) approaches to exploring potential vulns.

OpenVAS (and similar) are obviously super powerful tools for this, but I would be nervous encouraging their use too widely, as hosting providers and DDoS protection tools may detect and block, or, worse, they may actually crash an application or server.  I prefer to deploy those last, if at all, and in as controlled an environment as possible.
