### ISSUE TITLE
Add additional tool for Web application vulnerability Scanning

### ISSUE THREAD

**Issue by hackatom** [SAFETAG/SAFETAG#311]
I'm using this awesome tool https://portswigger.net/burp/help, Basically used for manual testing of web and mobile applications, and a good addition to [/exercises/vulnerability_scanning/](https://github.com/SAFETAG/SAFETAG/tree/master/en/exercises/vulnerability_scanning)

**Comment by joncamfield** [comment]
I think an entire exercise just walking through burp would be useful to help auditors poke at websites balancing manual exploration with some pre-built tooling. Please be clear in identifying risks (flagging an account as being attacked, breaking/DoSing a site, etc. in the description.

**Comment by joncamfield** [comment]
Leaving this open to split Burp into a separate exercise.

**Comment by joncamfield** [comment]
With Variants per #315 seeming to be a "thing" now, closing this
