### ISSUE TITLE
Including binary files and/or hosted resources?

### ISSUE THREAD

**Issue by joncamfield** [SAFETAG/SAFETAG#316]
Multiple practitioners have been using different approaches, particularly in the pre and post audit survey/followup work, involving using Google Forms and formatted OpenOffice documents to collect input from organizations.

I would like to have a discussion thread here on what workflow and product make the most sense.  Ideally I wouldn't want to rely on an external service or binary files, but also accept that the "user" for
this are staff at orgs who need a usable form to fill in and send back, and need to do that in a secure fashion.  It'd be amazing if there was a markdown-y format that could be automated to transform
into a google form / word doc (might work?) / etc., but I fear that would be fragile and dependent on Google never tweaking Forms, and, as far as I can tell, the ability to "convert" spreadsheets to forms in Google Drive no longer works.

We could create a collection of shared forms in Google Drive and link them in, include a (hopefully small) number of forms as ODT files within this or another repo, or leave this as an exercise to individual auditors to take the questions and guidance from the SAFETAG content and adapt to their communities/needs?

**Comment by vdml** [comment]
I am the one who currently uses Google Forms) I believe that @jmatsushita 's [suggestion to use Commonmark]
(https://github.com/iilab/contentascode/issues/59) is the most promising. I would really like to play with it for some time and migrate some of my stuff to it though, to make sure that it is actually easy to convert it into formats which would allow the auditors to capture and analyze information during the assessment.

**Comment by joncamfield** [comment]
Re-energizing this issue, as more auditors are developing helper materials; and it would be great to share these more effectively.

I am wary of relying completely on "hosted" solutions which don't have a backup of the file in the github repo (so not just google/cryptpad/dropbox/etc. shared docs)

(Overall, I would prefer minimizing these and/or using markdown formatting to make rough versions inside the SAFETAG activities where possible, enabling auditors to copy into their own doc and customize without starting from zero, but that's a bigger lift)

Obviously, these documents would not get built into SAFETAG as a PDF or in the web version, so we also have to decide where to "host" them to be able to be linked to.  Perhaps a companion repo of just documents?

**Comment by cguerrave** [comment]
If we generate a few files which aren't that heavy (i.e. odts) it doesn't make sense to have them inside the repo? I think it shouldn't be that complicated of heavy but maybe I'm missing some point

**Comment by joncamfield** [comment]
My only concern there is that it makes linking directly to them from generated guides ugly (not that a "plain" repo with just files would be significantly better, mind you)
