### ISSUE TITLE
There is no "fonts folder"

### ISSUE THREAD

**Issue by poser** [SAFETAG/SAFETAG#318]
The build instructions for Spanish content in the last code snippet [here](https://github.com/SAFETAG/SAFETAG/blob/master/INSTALL.md#building-documentation-and-reports) say 

> Note: The Spanish version has a slightly modified style to fit the contents. You will need to manually copy the fonts folder from the top-level styles directory into es/styles.

but there is no `fonts` folder in `.../safetag/styles`. (Nor is there a `.../safetag/es/styles` folder.)

**Comment by joncamfield** [comment]
The safetag makefile downloads and creates the font folder (https://github.com/SAFETAG/SAFETAG/blob/master/makefile).

This may be built in to the newer version of DocBuilder, and is obsolete, or is an appendix-like item remaining in the SAFETAG install process that could be built in better.

In either case, the DocBuilder was, last I looked, having some dependency problems. We haven't dedicated much time to fixing it as we're moving to Jun's Content as Code setup, @kakron has managed to get it working, and the TL;DR is that you need to run it in debug mode, grab the HTML output, and PDF/docify/whatever you like from there.  You can even add some js to build a ToC and get this: https://safetag.org/guide/
