### ISSUE TITLE
Screenshots for activities and instructions

### ISSUE THREAD

**Issue by hackatom** [SAFETAG/SAFETAG#320]
(Tried looking for any close issues regarding this) 

Just like any common guides and documentations, a screen capture is always helpful. Need to know your thoughts on this.

**Comment by joncamfield** [comment]
We opted to avoid and minimize this for a few reasons -- a goal for SAFETAG is to have it more actively translated, and maintaining screenshots across multiple languages is challenging, keeping up to date with interface changes of tools requires ongoing maintenance, moreso than text descriptions of how/why, and finally, most of SAFETAG guidance should be a level slightly above the basic tool use (to the extent there are existing external, maintained guides to point to).

That said, a few screenshots and diagrams can be very useful, but where possible making them SVGs (with translatable embedded strings).  Before diving too deep, will be worth pinging @jmatsushita for any design constrains to consider with the conversion/migration process

**Comment by hackatom** [comment]
Thanks @joncamfield!
