### ISSUE TITLE
Adding Meta data to methods and exercises

### ISSUE THREAD

**Issue by joncamfield** [SAFETAG/SAFETAG#334]
At the SAFETAG Stewards meeting, other orgsec community discussions, and in adapting SAFETAG to a Content as Code approach, it would be useful to collect what metadata would be most useful to include in methods and/or exercises.

Some conceptual "tags":
* remote (can be done remotely, see #275 )
* time required (with value)
* skills required (list)

Also a collection of metadata around what types of organizations a specific exercise is best for, e.g.:
* Org size / structure (one office, hub-and-spoke, decentralized...)
* Org infrastructure (desktop OS, service/cloud providers...)
* Capabilities of relevant threat actors? Intent?

Similarly, we can construct playlists around some organizational archetypes (e.g. "Small, decentralized media organization facing an aggressive state-level actor" , "Small health NGO working on HIV/Aids outreach in country known to surveil and raid NGO offices").  It could be useful for both tool developers (think https://usable.tools/personas/) with visuals to capture some of the above metadata (I'm imagining something like the 2-axis "persona characteristics" charts by @gusandrews: https://medium.com/@gusandrews/user-personas-for-privacy-and-security-a8b35ae5a63b)  to capture key org variables (capacity x threat ?), and an iconography (like the UN SDG icons? http://www.un.org/sustainabledevelopment/news/communications-material/) for org missions (information/media, health, human rights, etc.)

**Comment by joncamfield** [comment]
I'm getting close to pushing metadata in at the index.md level, at least as a pilot test to see how it goes, and see if we can update the document builder to "process" some of these and make icons and/or transform them into visible text in its output.

### Methods:

* Authors: 
* Info_required: [info flow]
* Info_provided: [info flow]


### Exercises:

* Authors: 
* Skills_required: 
* Approach: [Technical, Research, Interpersonal]
* Time_required_minutes: #
* Materials_required: [tags?]
* Org_size_under: [5, 20, 50, 100, 500]
* Remote_options: [none, fully, with-support, partially, review-only]

### Curricula:

* Authors: 
* Skills_required: 
* Skills_trained:

**Comment by joncamfield** [comment]
@florianap @mfc @mfelaco @cguerrave  @jmatsushita @seamustuohy  @poser - would appreciate any inputs here before I go crazy with some regex (I'm sure regex can parse markdown, since it's so capable with html... (old joke: https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454))

**Comment by seamustuohy** [comment]
I remember what happened last time we tried to update the SAFETAG metadata with regex... 
![Image of man looking at fire](https://media.giphy.com/media/QQQoLTqkm7v3y/giphy.gif)

[I made you a little script to do this for you.](https://gist.github.com/seamustuohy/1f52b3ad74da0c39cd3b6ca97e427e63) *The gist also includes two shell scripts. One that shows the dependencies, and one that shows how to run it on all the English SAFETAG indexes.*

The script will 
* load a markdown file, 
* read the current metadata, 
* add the new metadata (using "unknown" for all the values that don't exist)
* write the file back with the new metadata included.

At it's simplest level it looks like this. (Debugging on so you can see what is happening)

```bash
method="/home/user/SAFETAG/en/methods/responsive_support.guide.md"
python3 safetag_metadata_convert.py --debug \
                                    --doc  "${method}" \
                                    --doctype methods 
```

If you just wanted to add metadata to all the English indexes you could do it like this.

```sh
SAFETAG_DIR="/home/user/SAFETAG"
declare -a doctypes=("methods" "adids")
for doctype in "${doctypes[@]}"; do
    for i in "${SAFETAG_DIR}"/en/"${doctype}"/*.md; do
        python3 safetag_metadata_convert.py -d "${i}" -t "${doctype}" -v
    done
done

# Excercises are different
for ex_folder in $(find "${SAFETAG_DIR}"/en/exercises/* -type d); do
    index="${ex_folder}/index.md"
    if [[ -f "${index}" ]]; then
        python3 safetag_metadata_convert.py -d "${index}" -t exercises -v
    fi
done
```

**Comment by joncamfield** [comment]
This is epic. (side note: We should make a repo or wiki of useful hacks/scripts/command line recipes for use with SAFETAG)
Thanks to this, I am working on an initial commit for the metadata branch (https://github.com/SAFETAG/SAFETAG/tree/metadata) to test this out.  As I work through it, I am using these guiding principles:

* Minimize terms (this is hard, but I'm trying, some of the technical skills are ... challenging to "identify")
* Time estimate currently presumes an experienced auditor who doesn't need to spend time on their personal setup (just specific org setup needs), and is calculated for the "max org size the exercise is listed for.

**Comment by joncamfield** [comment]
Finally closing this thread; the soon-to-launch updated version is full of metadata
