### ISSUE TITLE
[4.2 Context Research] resources -- 404 error

### ISSUE THREAD

**Issue by megdeb** [SAFETAG/SAFETAG#343]
404 error here: 

What general cyber-security threats is the organization facing?
--> Reports: "McAfee Threat Trends Papers" (McAfee)

**Comment by hackatom** [comment]
This could be because it's outdated, and I'm not sure pulling it back from archive can be of use. Maybe we can update this with the latest report?

https://www.mcafee.com/us/resources/reports/rp-quarterly-threats-dec-2017.pdf

**Comment by joncamfield** [comment]
Fixed a badly formatted URL link. Next time we push to /guide it will fix this.
