### ISSUE TITLE
Complete Advanced Threat workshop content inclusion

### ISSUE THREAD

**Issue by joncamfield** [SAFETAG/SAFETAG#359]
- [x] original Advanced threat content merge: https://github.com/SAFETAG/SAFETAG/pull/323
- [x] high-risk interview question mods: https://github.com/SAFETAG/SAFETAG/pull/344 ; https://github.com/SAFETAG/SAFETAG/pull/347
- [x] Network Scanning changes: https://github.com/SAFETAG/SAFETAG/pull/346
- [x] Triage workflow and incident response: https://github.com/SAFETAG/SAFETAG/pull/358 
- [x]  Updated method: https://github.com/SAFETAG/SAFETAG/pull/348
- [ ]  Push as a release and update safetag.org/guide

@SAFETAG/advisory-board @megdeb @mfc @florianap Any other content remaining to add in?

**Comment by mfc** [comment]
I think we are still missing the forensic capture content that @dgfscr worked on. @florianap has edited it and provided feedback, and I think it is close to being a pull request.

**Comment by florianap** [comment]
Now the module on forensic capture is in a pull request: https://github.com/SAFETAG/SAFETAG/pull/360

**Comment by joncamfield** [comment]
Add https://securitybytes.io/blue-team-fundamentals-part-two-windows-processes-759fe15965e2 to the process exploration section

**Comment by joncamfield** [comment]
The IOC capture section has not been integrated either. @megdeb and I met yesterday to review that and think it needs to be merged in as a separate activity, and we need to better frame the triage and opsec / prep pieces across that and the evidence capture work.

We are also considering moving the incident response piece back out to its own exercise, change the existing IR piece to be just a part of the agreement creation section, and use that to "hold" some of the triage work.

**Comment by joncamfield** [comment]
And another resource: https://github.com/hslatman/awesome-threat-intelligence
