### ISSUE TITLE
Add DNSTwist

### ISSUE THREAD

**Issue by joncamfield** [SAFETAG/SAFETAG#362]
https://github.com/elceef/dnstwist

Possibly use JtR to build a better dictionary for the domains using leet and other replacement patterns?

**Comment by hackatom** [comment]
Cool stuff. Will incident_response be a good place to put this as a variant? fraud_domain or fraud_site etc?

**Comment by blazman** [comment]
Added as a variant to https://guide.safetag.org/activities/web_vulnerability_assessment/ (open to other suggestions to move it).

Also flagging a separate discussion - the strategy of using "Variant:" to specify a tool walkthrough isn't really ideal. These could probably be pulled out as activities, or perhaps become another content type.

**Comment by joncamfield** [comment]
We wanted to group tools which all met very similar goals together in a way that was a bit more cohesive than a set of diverse activities, there's a decent discussion here: https://github.com/SAFETAG/SAFETAG/issues/315  .  I don't think "variants" are the most ideal solution for sure, so another solution (that still, ideally, doesn't create a ton of activities where only the specific tool walkthrough is different) is welcome.
