### ISSUE TITLE
Github-git-cheatsheet

### ISSUE THREAD

**Issue by hackatom** [SAFETAG/SAFETAG#375]
Additional resource to contributing to SAFETAG

https://services.github.com/on-demand/downloads/github-git-cheat-sheet.pdf

**Comment by megdeb** [comment]
Perhaps we can add here? Include a section on 

"A Note on GitHub Contributions"
* When creating new content, first create a new branch and label appropriately (example: "exercise_[NAME]" or "method_[NAME]"
* GitHub CheatSheet
https://github.com/SAFETAG/SAFETAG/blob/master/en/document_matter/CONTRIBUTING.md
