### ISSUE TITLE
Update recon-ng activity to latest release

### ISSUE THREAD

**Issue by joncamfield** [SAFETAG/SAFETAG#400]
Recon has moved to github and the install and setup process now requires adding modules explicitly from their marketplace: https://github.com/lanmaster53/recon-ng/

Also see https://github.com/kpcyrd/sn0int ; inspired by recon and developed during its development lapse

**Comment by blazman** [comment]
Working on this... have updated the install links but will have to learn more to see how the walk-through needs to be updated.

**Comment by blazman** [comment]
mark for closure (sn0int looks nice... could be a new issue for future development)

**Comment by joncamfield** [comment]
moved sn0int to its own issue: https://github.com/SAFETAG/SAFETAG/issues/409

**Comment by joncamfield** [comment]
closed by #408
