### ISSUE TITLE
[Update] 3.3 Report Creation - Resources

### ISSUE THREAD

**Issue by megdeb** [SAFETAG/SAFETAG#402]
**Add Zeltser guidance and cheat sheet:**
https://zeltser.com/security-assessment-report-cheat-sheet

**Add Zeltser guidance on executive summary.**
https://zeltser.com/executive-summary-for-security-assessment-report-tips

**Add Zeltser sample report of fictitious company.**
https://zeltser.com/auditing-unix-systems/

**Comment by blazman** [comment]
Have added these in an upcoming PR to report creation resources
