### ISSUE TITLE
Mismatched method/activity structures

### ISSUE THREAD

**Issue by LanesGood** [SAFETAG/SAFETAG#434]
There are lots of random activitiyes tagged to the introductory opsec method, and then no activities in the physical/operational secutrity actual method.

We need to review the most updated SAFETAG built PDF to this to make sure activities are matched up.

**Comment by LanesGood** [comment]
It appears that the first selected Method Title and Method Summary are not rendering in the exported PDF, so they appear to be swallowed by the preceding section (Operational Security in introduction).

This relates to a previously noted issue that the Methods section heading no longer prints correctly. cc @vgeorge

**Comment by rlafuente** [comment]
This should be fixed in the development version. Please try this out on dev.safetag.org and feel free to close this issue if the bug's gone.

(turns out that PDFkit really wants an empty line between headings, and behaves weirdly if they're not there.)
