### ISSUE TITLE
File Attachments

### ISSUE THREAD

**Issue by LanesGood** [SAFETAG/SAFETAG#436]
Can we enable attaching files (Docs, spreadsheets) to activities (often for templates for the activity work)

If this is managed via "media" can we do folders there or nah? https://github.com/netlify/netlify-cms/issues/2794 ? https://community.netlify.com/t/understanding-the-netlifycms-media-library-functionality/18941 ? (add a "public" media library for all resource files?)

**Comment by LanesGood** [comment]
@joncamfield Would users expect these files to be downloadable from the front end of the site (ex: activity pages)? Would they simply be linked in the PDF?

**Comment by joncamfield** [comment]
Ideally the attachments would be linked in both the web version and via the PDF
