### ISSUE TITLE
Ordering of Audit activities?

### ISSUE THREAD

**Issue by LanesGood** [SAFETAG/SAFETAG#439]
pre-audit, audit, post-audit buckets for ordering

**Comment by LanesGood** [comment]
By "Activities" in the title here, do we mean "Methods"?

Can the order be provided in a numbered list? I believe it's ok to have some items ordered and some added without ordering.

**Comment by joncamfield** [comment]
Yes, sorry, "Methods" 

And a tentative "yes" re numbered list? Regardless of whether we make a numbered list or not, Methods will appear in a linear fashion when listed, so we might as well apply an order to that.

**Comment by blazman** [comment]
I just came into the issues page to make this same suggestion. To make sense of SAFETAG it really needs to be presented in a rough chronological order of methods. Right now the order at #allMethods and guide-builder don't match the order as presented in the SAFETAG guide. Activities also don't seem to be any particular order at the moment, including alphabetical.

**Comment by joncamfield** [comment]
(also noting that any custom ordering should be reflected in the pdf export as well as somehow updating the URL for sharing in the same order)

**Comment by joncamfield** [comment]
A user creating a guide should be able to order (drag/drop?) the methods (and ideally activities within a method).

QUESTIONS:

* Should a user be able to "override" activity/method linkages and move an activity into a different method? 
* Should a user be able to "override" build in pre/during/post method ordering?
