### ISSUE TITLE
Create Debian package

### ISSUE THREAD

**Issue by seamustuohy** [SAFETAG/SAFETAG#44]
The current make based installer is a dependency hell. As such, a debian package is the best path forward. 

There are concerns.
- What is the best installation path for a package that we desire the user to edit. 
- Do we add basic git pull ability into the package so that the user can keep their SAFETAG content up to date before they build?
- Should this be a seperate repository that pulls from the git content and places it in a specific directory?
- How do we best incorporate GUI control into a seperate package like this?

**Comment by elationfoundation** [comment]
This issue should be moved to the SAFETAG document creator repository issue cue once it is separated from this repository.

**Comment by joncamfield** [comment]
Moved to https://github.com/OpenInternet/Documentation-Builder/issues/7
