### ISSUE TITLE
Activity did not show in the pdf

### ISSUE THREAD

**Issue by LanesGood** [SAFETAG/SAFETAG#442]
Generated the guide with the advanced persistent threats method and one activity and it did not show correctly in the pdf

Screenshots here: https://docs.google.com/document/d/1bR5y-RCqVkffyqzADg-e9XVp7V96ROk560fLAdr3FF4/edit?usp=sharing

**Comment by blazman** [comment]
+1 issue occurs for me when following the same steps. The Advanced Threats method begins in the PDF with the "Purpose" section and does not have a section heading (or "summary section". Likewise cut-off images and agreed it would be good to reduce whitespace on some screens.

**Comment by blazman** [comment]
Likewise Page 12 of the current guide https://guide.safetag.org/guides/Safetag_full_guide.pdf the 'Data Assessment' method heading and summary is missing, it just goes directly into Purpose.

**Comment by rlafuente** [comment]
I think this one's related to #434, which is fixed in dev and I think the fix also deals with this issue. Can someone test and confirm?
