### ISSUE TITLE
Merge safetag.org and guide.safetag.org

### ISSUE THREAD

**Issue by joncamfield** [SAFETAG/SAFETAG#451]
Merge the existing website content into the gatsby site for one unified website.

**Questions**
- Will this work with the Netlify CMS approach? How will safetag.org web pages and blogs show up versus safetag guide content?
- Will the blog need its own subdomain/site (for blogging and blog-linked images?)

Linked more specific issues
- Move current guide.safetag.org main page to /guide
- Create new homepage
- Add blog feature #452 
- ~~Add Reveal.js presentation feature (via static html pages) #453~~
- Add static pages (nav, styling options, template/content) (to capture COC, credits, contact, license, etc. pages) #454
- Add front matter/intro and appendix pages (currently captured as Guide Sections) 
- rename 'master' branch to 'main'

**Comment by rlafuente** [comment]
I think these are all addressed now, can you confirm?
