### ISSUE TITLE
Two blank activities in guide builder 

### ISSUE THREAD

**Issue by globalashm** [SAFETAG/SAFETAG#462]
- "Prepare for Uncertainty" is a blank activity listed under the Preparation method in the custom generation section of the site (does not display on the main activities page - https://guide.safetag.org/activities/) Link: https://guide.safetag.org/activities/safetag_audit_timeline
- "Identifying Recommendations" is a blank activity listed under the Report Creation and Recommendation Development method in the custom generation section of the site (does not display on the main activities page) Link: https://guide.safetag.org/activities/identifying_recommendations

**Comment by joncamfield** [comment]
Moving this to #469
