### ISSUE TITLE
Images not displaying properly

### ISSUE THREAD

**Issue by globalashm** [SAFETAG/SAFETAG#464]
- Risk vs Difficulty, Risk vs Likelihood and Impact vs Severity images: https://guide.safetag.org/activities/risk_matrix
  - Level Up Backup Matrix Example: https://guide.safetag.org/activities/sensitive_data

**Comment by blazman** [comment]
These were just missing images. I checked for any other missing images, uploaded them, and edited the image path in the associated content file.
