### ISSUE TITLE
Empty Activities

### ISSUE THREAD

**Issue by LanesGood** [SAFETAG/SAFETAG#469]
"Identifying Recommendations": https://guide.safetag.org/activities/identifying_recommendations
- I don't see evidence of this one in the `master` branch except for this empty reference file: https://github.com/SAFETAG/SAFETAG/blob/dev/en/references/identifying_recommendations.md

Vulnerability research: https://guide.safetag.org/activities/vulnerability_research
- This page works as expected. The summary is empty in the document, but is required according to the markdown structure configuration. This results in the `[object Object]` rendering. Suggested change: add a summary. Alternatively, make summaries optional

Safetag Audit Timeline: https://guide.safetag.org/activities/safetag_audit_timeline
- It doesn't appear that this should be an activity, and I believe is being incorrectly added to this folder by the processing script.

**Comment by joncamfield** [comment]
Merging in #462, @globalashm  also found :


    "Prepare for Uncertainty" is a blank activity listed under the Preparation method in the custom generation section of the site (does not display on the main activities page - https://guide.safetag.org/activities/) Link: https://guide.safetag.org/activities/safetag_audit_timeline
    
    "Identifying Recommendations" is a blank activity listed under the Report Creation and Recommendation Development method in the custom generation section of the site (does not display on the main activities page) Link: https://guide.safetag.org/activities/identifying_recommendations
