### ISSUE TITLE
Eliminating metro map/information flow sections

### ISSUE THREAD

**Issue by blazman** [SAFETAG/SAFETAG#478]
Proposal to eliminate the metro map/Flow of Information graphic and sections from the full resource. 

In my view it adds more confusion than clarity. It adds complexity and meta-analysis which isn't immediately useful to the reader.

**Comment by joncamfield** [comment]
I've heard this from multiple sources; I think removing the map and leveraging the metadata for methods going forward makes sense.

**Comment by blazman** [comment]
Ok, I'll clean them out then close this issue. Hopefully we can add more intuitive visual elements in the future, but the site is looking great so already a big aesthetic improvement

**Comment by blazman** [comment]
Removed/commented out with https://github.com/SAFETAG/SAFETAG/commit/1151b1bb8a90c3ff960ff6b8b50c862e2f1a76cb

**Comment by blazman** [comment]
Confirmed to work in PDF generator as well
