### ISSUE TITLE
Find a new location for Activity list on Methods page

### ISSUE THREAD

**Issue by blazman** [SAFETAG/SAFETAG#484]
Populating the links to Activities at the bottom of the Methods page makes it easy to miss that they exist, or what relation they have to the Method. For instance see the Preparation Method - https://guide.safetag.org/methods/preparation - the visitor will have to scroll through several page-lengths of resources to find out that there are activities linked to the Method.

Not sure of the best solution. Possibly putting it in the sidebar (I see on mobile devices the sidebar collapses into a single column below Summary, that could still work well)

**Comment by rlafuente** [comment]
There's a new activity section on the sidebar to deal with this in the development version. Feel free to check and close the issue in case it's dealt with!
