### ISSUE TITLE
Update interview goals to include a smaller sub-set of KEY goals

### ISSUE THREAD

**Issue by seamustuohy** [SAFETAG/SAFETAG#58]
- Break the ice
- establish your authority/expertiese
- [learn as much as possible](https://github.com/OpenInternet/SAFETAG/blob/dev/content/guides/interviews/examples/outputs_needed.md)

**Comment by elationfoundation** [comment]
Closed as interviews has been removed.

**Comment by elationfoundation** [comment]
It was actually just moved to be an activity... my bad.

**Comment by joncamfield** [comment]
Closing this with the Cap worksheet: https://guide.safetag.org/activities/capacity_assessment_cheatsheet
